version: "3"
services:
  backend:
    image: docker.pkg.github.com/johanneshiry/weinretter/wr_backend:latest
    build: 
      context: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend: 
    image: docker.pkg.github.com/johanneshiry/weinretter/wr_frontend:latest
    build: 
      context: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"   
    
  mongo:
    image: mongo
    container_name: mongocontainer
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db

