version: "3"
services:
  backend:
    container_name: wrbackend
    build: 
      context: ./backend
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN # Variable is provided by host
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:5001:5001"
    depends_on:
      - mongo

  frontend: 
    container_name: wrfrontend
    build: 
      context: ./frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    
  mongo:
    image: mongo
    container_name: mongocontainer
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - /data/db:/data/db

