version: "3"
services:
  backend:
    image: docker.pkg.github.com/johanneshiry/weinretter/wr_backend:latest
    container_name: wrbackend
    build: 
      context: ./backend
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - mongo

  frontend: 
    image: docker.pkg.github.com/johanneshiry/weinretter/wr_frontend:latest
    container_name: wrfrontend
    build: 
      context: ./frontend
    restart: unless-stopped
    ports:
      - "80:3000"
      - "443:3443"
    
  mongo:
    image: mongo
    container_name: mongocontainer
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db

