name: Docker

on:
  push:
    branches:
      - dev


  # Run tests for any PRs.
  pull_request:

env:
  FRONTEND_IMAGE_NAME: wr_frontend_dev
  BACKEND_IMAGE_NAME: wr_backend_dev


jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build backend image
        run: docker build backend --file backend/Dockerfile --tag wr_backend_dev

      - name: Build frontend image
        run: docker build frontend --file frontend/Dockerfile --tag wr_frontend_dev
            
  deploy:
       needs: build
       runs-on: ubuntu-latest
       if: github.event_name == 'push'

       steps:

         - name: ssh
           run: |
               mkdir -p ~/.ssh
               eval $(ssh-agent -s)
               bash -c 'ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")'
               ssh deploy@ec2-54-86-155-155.compute-1.amazonaws.com -o StrictHostKeyChecking=no "cd Weinretter && git pull && docker-compose --file dev.docker-compose.yml up -d --force-recreate --build"
  
